stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: $DOCKER_USERNAME/laravel-10-boilerplate-task

default:
  interruptible: true
  retry: 1

workflow:
  rules:
    - when: always

test:
  stage: test
  image: docker:26
  services:
    - name: docker:26-dind
      command: ["--tls=false"]
  script:
    - docker compose up -d --build
    - docker compose exec -T app composer install --no-interaction --prefer-dist
    - docker compose exec -T app cp -n .env.example .env || true
    - docker compose exec -T app php artisan key:generate
    - docker compose exec -T app php artisan migrate --force
    - docker compose exec -T app php artisan test
  after_script:
    - docker compose logs --no-color || true
    - docker compose down -v || true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_COMMIT_BRANCH =~ /^(development|staging|main|master)$/

build:
  stage: build
  image: docker:26
  services:
    - name: docker:26-dind
      command: ["--tls=false"]
  needs: ["test"]
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY
  script:
    - export TAG="${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:$TAG -t $DOCKER_REGISTRY/$DOCKER_IMAGE:${CI_COMMIT_REF_SLUG}-latest .
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$TAG
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:${CI_COMMIT_REF_SLUG}-latest
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(development|staging|main|master)$/
      when: on_success

deploy_development:
  stage: deploy
  image: alpine:3.19
  needs: ["build"]
  before_script:
    - apk add --no-cache bash curl
    - wget -qO /usr/local/bin/helm https://get.helm.sh/helm-v3.15.4-linux-amd64.tar.gz || true
  script:
    - echo "Simulating deploy to development using helm dry run"
    - echo "Image: $DOCKER_REGISTRY/$DOCKER_IMAGE:${CI_COMMIT_REF_SLUG}-latest"
    - echo "helm upgrade --install laravel ./helm/laravel-app --namespace development --create-namespace --set image.repository=$DOCKER_REGISTRY/$DOCKER_IMAGE --set image.tag=${CI_COMMIT_REF_SLUG}-latest --dry-run"
  environment:
    name: development
  rules:
    - if: $CI_COMMIT_BRANCH == "development"

deploy_staging:
  stage: deploy
  image: alpine:3.19
  needs: ["build"]
  before_script:
    - apk add --no-cache bash curl
  script:
    - echo "Simulating deploy to staging using helm dry run"
    - echo "helm upgrade --install laravel ./helm/laravel-app --namespace staging --create-namespace --set image.repository=$DOCKER_REGISTRY/$DOCKER_IMAGE --set image.tag=${CI_COMMIT_REF_SLUG}-latest --dry-run"
  environment:
    name: staging
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"

deploy_production:
  stage: deploy
  image: alpine:3.19
  needs: ["build"]
  before_script:
    - apk add --no-cache bash curl
  script:
    - echo "Simulating deploy to production using helm dry run"
    - echo "helm upgrade --install laravel ./helm/laravel-app --namespace production --create-namespace --set image.repository=$DOCKER_REGISTRY/$DOCKER_IMAGE --set image.tag=${CI_COMMIT_REF_SLUG}-latest --dry-run"
  environment:
    name: production
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|master)$/
