stages:
  - sts
  - init
  - plan
  - apply

image:
  name: hashicorp/terraform:1.10
  entrypoint: [""]

variables:
  TF_ENV_PATH: laravel-10-boilerplate-infra-task/environments/dev

########################
# SHARED AWS OIDC SCRIPT
########################

.aws_oidc_setup: &aws_oidc_setup
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  before_script:
    - apk --no-cache add curl python3 py3-pip
    - pip3 install --no-cache-dir awscli --break-system-packages
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws sts get-caller-identity

########################
# STS
########################

sts:
  stage: sts
  <<: *aws_oidc_setup
  script:
    - echo "OIDC authentication successful"

########################
# INIT
########################

init:
  stage: init
  <<: *aws_oidc_setup
  script:
    - cd ${TF_ENV_PATH}
    - terraform init -reconfigure -input=false

########################
# PLAN
########################

plan:
  stage: plan
  <<: *aws_oidc_setup
  script:
    - cd ${TF_ENV_PATH}
    - terraform init -reconfigure -input=false
    - terraform validate
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - ${TF_ENV_PATH}/tfplan
    expire_in: 1 day

########################
# APPLY
########################

apply:
  stage: apply
  <<: *aws_oidc_setup
  needs: ["plan"]
  when: manual
  allow_failure: false
  script:
    - cd ${TF_ENV_PATH}
    - terraform init -reconfigure -input=false
    - terraform apply tfplan
